In [85]:
import pandas as pd
import numpy as np

In [72]:
df=pd.read_csv("titanic.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [73]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [74]:
input=df.drop('Survived',axis='columns')
target=df.Survived

In [75]:
input.head()

Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

In [76]:
input.Sex=input.Sex.map({'male':1,'female':2})

In [77]:
input.head()

Pclass  Sex   Age     Fare
0       3    1  22.0   7.2500
1       1    2  38.0  71.2833
2       3    2  26.0   7.9250
3       1    2  35.0  53.1000
4       3    1  35.0   8.0500

In [82]:
input.isnull()

Pclass    Sex    Age   Fare
0     False  False  False  False
1     False  False  False  False
2     False  False  False  False
3     False  False  False  False
4     False  False  False  False
..      ...    ...    ...    ...
886   False  False  False  False
887   False  False  False  False
888   False  False   True  False
889   False  False  False  False
890   False  False  False  False

[891 rows x 4 columns]

In [87]:
input.isnull().sum()

Pclass      0
Sex         0
Age       177
Fare        0
dtype: int64

In [89]:
not_zero_accepted=['Age']
for i in not_zero_accepted:
    input[i]=input[i].replace(0,np.NaN)

In [97]:
mean=int(input['Age'].mean(skipna=True))
mean

29

In [98]:
input['Age']=input['Age'].replace(np.NaN,mean)

In [104]:
input.Age.tail()

886    27.0
887    19.0
888    29.0
889    26.0
890    32.0
Name: Age, dtype: float64

In [105]:
input.head()

Pclass  Sex   Age     Fare
0       3    1  22.0   7.2500
1       1    2  38.0  71.2833
2       3    2  26.0   7.9250
3       1    2  35.0  53.1000
4       3    1  35.0   8.0500

In [106]:
target.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [107]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [108]:
X_train,X_test,y_train,y_test=train_test_split(input,target,test_size=0.3,random_state=1)

In [113]:
len(X_train)

623

In [117]:
from sklearn import tree
model=tree.DecisionTreeClassifier()

In [118]:
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [119]:
model.score(X_test,y_test)

0.75

In [123]:
y_pred=model.predict(X_test)
y_pred

array([1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0], dtype=int64)

In [124]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.74      0.86      0.80       153\n           1       0.76      0.61      0.68       115\n\n    accuracy                           0.75       268\n   macro avg       0.75      0.73      0.74       268\nweighted avg       0.75      0.75      0.74       268\n'

In [125]:
confusion_matrix(y_test,y_pred)

array([[131,  22],
       [ 45,  70]], dtype=int64)

In [126]:
accuracy_score(y_test,y_pred)

0.75

In [127]:
input.tail()

Pclass  Sex   Age   Fare
886       2    1  27.0  13.00
887       1    2  19.0  30.00
888       3    2  29.0  23.45
889       1    1  26.0  30.00
890       3    1  32.0   7.75

In [129]:
model.predict([[1,2,19.0,30.00]])

array([1], dtype=int64)

In [130]:
model.predict([[3,2,29.0,23.45]])

array([1], dtype=int64)

In [133]:
model.predict([[1,,26.0,10.00]])

array([0], dtype=int64)